DROP TABLE IF EXISTS teams;
CREATE TABLE teams (
	team_pk INTEGER PRIMARY KEY AUTOINCREMENT,
	team TEXT NOT NULL
);

DROP TABLE IF EXISTS players;
CREATE TABLE players (
	player_pk INTEGER PRIMARY KEY AUTOINCREMENT,
	player TEXT NOT NULL
);

DROP TABLE IF EXISTS matches;
CREATE TABLE matches (
	match_pk INTEGER PRIMARY KEY AUTOINCREMENT,
	teama INTEGER NOT NULL,
	teamb INTEGER NOT NULL,
	teama_score INTEGER NOT NULL,
	teamb_score INTEGER NOT NULL,
	status_id INTEGER DEFAULT 0
);

DROP TABLE IF EXISTS team_memberships;
CREATE TABLE team_memberships (
	team_pk INTEGER PRIMARY KEY AUTOINCREMENT,
	team TEXT NOT NULL
);

DROP TABLE IF EXISTS status;
CREATE TABLE status (
	status_pk INTEGER PRIMARY KEY AUTOINCREMENT,
	status TEXT NOT NULL
);

INSERT INTO status (status_pk, status) VALUES
(0, "NOT PLAYED"),
(1, "TEAM A WINS"),
(2, "TEAM B WINS");

